version: "1"
rules:
  - base: master
    upstream: keldaanCommunity/pokemonAutoChess:prod
    mergeMethod: merge
    mergeUnstable: true
    mergeCommitMessage: "chore(sync): merge upstream changes"
