name: Sync fork with parent and resolve app/ conflicts

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: master

    - name: Add parent repository as upstream
      run: |
        git remote add upstream https://github.com/keldaanCommunity/pokemonAutoChess.git
        git fetch upstream

    - name: Merge upstream/master into your master, allowing unrelated histories
      run: |
        git merge upstream/master --no-ff --allow-unrelated-histories || echo "Merge conflict detected"

    - name: Automatically resolve conflicts in app/ directory
      if: failure() # Only run if there are merge conflicts
      run: |
        git checkout --theirs app/ || echo "No conflicts to resolve in app/"
        git add app/
        git commit -m "Automatically resolved conflicts in app/ by accepting upstream changes" || echo "Nothing to commit"

    - name: Push changes to your repository
      run: |
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
