name: Auto-merge conflicts for app/ directory

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Pull changes from master
      run: |
        git fetch origin master
        git merge origin/master
        
    - name: Configure Git for automatic merge
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Resolve conflicts by taking incoming changes for app/ directory
      run: |
        git checkout --theirs app/ || echo "No conflicts to resolve"
        git add app/ || echo "Nothing to add"
        git commit -m "Automatically resolved conflicts in app/ by taking incoming changes" || echo "Nothing to commit"
    
    - name: Push the resolved changes
      run: |
        git push origin ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
