name: Sync with upstream

on:
  workflow_dispatch: # allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *' # weekly sync

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set up Git user for GitHub Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/keldaanCommunity/pokemonAutoChess.git
          git fetch upstream

      - name: Merge upstream/prod into current branch with 'theirs' strategy
        run: |
          git merge upstream/prod --no-ff --allow-unrelated-histories -X theirs || echo "Merge conflict detected"

      - name: Keep local versions of custom files
        run: |
          git checkout --ours Dockerfile.custom entrypoint.custom.sh .github/workflows/*
          git add Dockerfile.custom entrypoint.custom.sh .github/workflows/*
          git commit -m "Keep local version of custom files" || echo "No changes to commit"

      - name: Push changes back to the repo
        run: |
          git push origin master
