name: Auto-merge conflicts for app/ directory

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch the latest master branch
      run: |
        git fetch origin master

    - name: Create a new branch for merging
      run: |
        git checkout -b keldaanCommunity-master master
        git pull https://github.com/keldaanCommunity/pokemonAutoChess.git master

    - name: Attempt to merge with master
      run: |
        git checkout master
        git merge --no-ff keldaanCommunity-master || echo "Merge conflict detected"

    - name: Resolve conflicts in app/ directory
      if: failure()
      run: |
        git checkout --theirs app/ || echo "No conflicts to resolve"
        git add app/ || echo "Nothing to add"
        git commit -m "Automatically resolved conflicts in app/ by taking incoming changes" || echo "Nothing to commit"

    - name: Push the resolved changes back to GitHub
      run: |
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
