name: Sync with Upstream and Build Docker Image

on:
  schedule:
    - cron: '0 1 * * *' # Runs at 1:00 AM every day
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  sync_and_build:
    runs-on: ubuntu-latest
    steps:
      # Sync with upstream repository
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set up Git user for GitHub Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/keldaanCommunity/pokemonAutoChess.git
          git fetch upstream

      - name: Merge upstream/prod into current branch with 'theirs' strategy
        run: |
          git merge upstream/prod --no-ff --allow-unrelated-histories -X theirs || echo "Merge conflict detected"

      - name: Keep local versions of custom files
        run: |
          git checkout --ours Dockerfile.custom entrypoint.custom.sh .github/workflows/* syncDatabase.js policy.md
          git add Dockerfile.custom entrypoint.custom.sh .github/workflows/* syncDatabase.js
          git commit -m "Keep local version of custom files" || echo "No changes to commit"

      - name: Push changes back to the repo
        run: |
          git push origin master

      # Build and deploy Docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.custom -t ${{ secrets.DOCKER_USERNAME }}/pokemon-auto-chess:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pokemon-auto-chess:latest
